apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml

replacements:
  - name: SECRETVALUE
    objref:
      apiVersion: v1
      kind: Secret
      name: secret01
      namespace: ns01
    fieldref:
      fieldpath: data.password

