apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml

# vars:
#   - name: SECRETVALUE
#     objref:
#       apiVersion: v1
#       kind: Secret
#       name: secret01
#       namespace: ns01
#     fieldref:
#       fieldpath: data.password

replacements:
- source:
    kind: Secret
    name: Secret01
    namespace: ns01
    fieldPath: data.password
  targets:
  - select:
      kind: ConfigMap
      name: cm01
    fieldPaths:
    - data.key01
